### ISSUE TITLE
qslack: using an exclamation mark (!) in search terms results in an error

### ISSUE THREAD

**Issue by Necior** [landmaj/qbot#18]
It seems like using an exclamation mark in search terms gives an error.

# Steps to reproduce

In `CHANNEL_FORTUNKI` write e.g. `!szukaj -- fortunka !asdf`.

# Expected behavior

Qbot returns search results (possibly none).

# Observed behavior

Qbot replies with the following message:

```
ERROR: INTERNAL
```

**Comment by landmaj** [comment]
The error happens with other special characters as well. I found this explanation: https://stackoverflow.com/a/46529832
