### ISSUE TITLE
Migrate from Slack to Matrix

### ISSUE THREAD

**Issue by Necior** [landmaj/qbot#23]
As discussed in private, we'd like to migrate from proprietary Slack to open Matrix.

I believe it's a great opportunity to perform a gradual migration instead of doing A Big Rewrite.

I propose the following plan:

1. write platform-agnostic interfaces (what kind of incoming messages are there? what about outgoing messages?);
2. https://github.com/landmaj/qbot/issues/24;
3. move Slack-related code to its own module;
4. implement a Matrix client;
5. move plugins (possibly one by one) from Slack to Matrix while paying special attention to the bridge behavior.

**Comment by Necior** [comment]
@landmaj, I'd be grateful for your opinion on the above. Any suggestions?

I'm happy to work on this issue. In fact, I've already started doing some refactoring.

**Comment by landmaj** [comment]
Looks great, Qbot is in a dire need of a refactor anyway.

**Comment by Necior** [comment]
Good, I'm on it! Expect some PRs :)
